eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  file:
    name: mi-log-aplicacion.log
  level:
    com:
      ms_torneo: DEBUG
    org:
      hibernate:
        SQL: DEBUG
    root: INFO
server:
  port: 8089
spring:
  application:
    name: ms-torneo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/db_torneo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: test
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html