spring.application.name=gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.compatibility-verifier.enabled=false

#Usuario
spring.cloud.gateway.server.webflux.routes[0].id=ms-usuario
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ms-usuario
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/usuarios/**

#Estadistica
spring.cloud.gateway.server.webflux.routes[1].id=ms-estadistica
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ms-estadistica
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/estadistica/**

#Arbitro
spring.cloud.gateway.server.webflux.routes[2].id=ms-arbitro
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ms-arbitro
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/arbitros/**

#Entrenador
spring.cloud.gateway.server.webflux.routes[3].id=ms-entrenador
spring.cloud.gateway.server.webflux.routes[3].uri=lb://ms-entrenador
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/entrenadores/**

#Eqipo
spring.cloud.gateway.server.webflux.routes[4].id=equipo
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ms-equipo
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/equipos/**

#Estadio
spring.cloud.gateway.server.webflux.routes[5].id=ms-estadio
spring.cloud.gateway.server.webflux.routes[5].uri=lb://ms-estadio
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/estadios/**

#Jugador
spring.cloud.gateway.server.webflux.routes[6].id=jugador
spring.cloud.gateway.server.webflux.routes[6].uri=lb://ms-jugador
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/jugadores/**

#Partido
spring.cloud.gateway.server.webflux.routes[7].id=ms-partido
spring.cloud.gateway.server.webflux.routes[7].uri=lb://ms-partido
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/partidos/**

#Posiciones
spring.cloud.gateway.server.webflux.routes[8].id=ms-posiciones
spring.cloud.gateway.server.webflux.routes[8].uri=lb://ms-posiciones
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/posiciones/**

#Torneo
spring.cloud.gateway.server.webflux.routes[9].id=ms-torneo
spring.cloud.gateway.server.webflux.routes[9].uri=lb://ms-torneo
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/torneos/**
