spring.application.name=ms-usuario


server.port=8090

spring.profiles.active=dev
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/